# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='projects',
            new_name='project',
        ),
    ]
