# Generated by Django 2.0.7 on 2018-07-08 20:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cartitem'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('discounted', django.db.models.manager.Manager()),
            ],
        ),
    ]
