# Generated by Django 2.0.7 on 2018-07-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180709_0118'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='contributor',
#            name='project',
#        ),
#        migrations.RemoveField(
#            model_name='project',
#            name='language',
#        ),
#        migrations.DeleteModel(
#            name='Contributor',
#        ),
#        migrations.DeleteModel(
#            name='Project',
#        ),
#        migrations.DeleteModel(
#            name='SourceLanguage',
#        ),
    ]
