# Generated by Django 2.0.7 on 2018-07-08 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_category_assignable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='customer_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CustomerDiscount'),
        ),
    ]
