# Generated by Django 2.0.7 on 2018-07-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180709_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdiscount',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
